version: '3'
services:

  flask-app:
    image: my-flask-app:latest
    ports:
      - "8000:8000"
    container_name: flask
    restart: always 
    networks:
        - app_tier
    volumes:
       - ./flask/:/app        
    command: gunicorn -w 1 -b 0.0.0.0:8000 app:app

  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
    networks: 
      - app_tier
    restart: "on-failure"

networks:  # 네트워크 이름 
  app_tier:
    driver: bridge  # 컨테이너를 bridge로 연결 