apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: example
spec:
  ports:
    - name: web-port
      port: 80
      targetPort: flask-port
  selector:
    app: webserver
  type: ClusterIP
