FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime


RUN apt-get -y update
RUN apt-get -y install python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install jupyter
RUN pip3 install pandas
RUN pip3 install matplotlib
RUN pip3 install seaborn
RUN pip3 install statsmodels
RUN pip3 install -U scikit-learn
